# Define pipeline stages
stages:
  - build
  - deploy

# Cache node_modules to speed up subsequent builds
cache:
  paths:
    - node_modules/

# Build job
build-frontend:
  stage: build
  image: node:20
  script:
    - echo "Installing frontend dependencies..."
    - npm install
    - export NODE_OPTIONS="--max-old-space-size=4096"
    - echo "Building frontend..."
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  only:
    - main
    - develop

# Deploy job
deploy-frontend:
  stage: deploy
  image: node:20
  before_script:
    - echo "Setting up SSH..."
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H ec2-54-164-58-149.compute-1.amazonaws.com >> ~/.ssh/known_hosts
  script:
    - echo "Deploying frontend to EC2..."
    - scp -r dist/ ubuntu@ec2-54-164-58-149.compute-1.amazonaws.com:/home/ubuntu/wavetrack-client
    - ssh ubuntu@ec2-54-164-58-149.compute-1.amazonaws.com "
      cd /home/ubuntu/wavetrack-client &&
      git pull origin develop &&
      sudo systemctl restart my-frontend-service &&
      sudo systemctl restart nginx"
  environment:
    name: production
    url: https://web.vottamean.com
  only:
    - main
    - develop
