# Define pipeline stages
stages:
  - build
  - deploy

# Cache node_modules to speed up subsequent builds
cache:
  paths:
    - node_modules/

# Build job
build-frontend:
  stage: build
  image: node:20
  script:
    - echo "Installing frontend dependencies..."
    - npm install
    - export NODE_OPTIONS="--max-old-space-size=4096"
    - echo "Building frontend..."
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  only:
    - main
    - develop

# Deploy job
deploy-frontend:
  stage: deploy
  image: node:20
  before_script:
    - echo "Current user: $(whoami)"  # Add this to check user context
    # Create .ssh directory in the home directory
    - mkdir -p $HOME/.ssh
    # Add the private key from the GitLab variable and remove carriage returns
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > $HOME/.ssh/wavetrack-deploy.pem
    # Set the correct permissions for the private key
    - chmod 600 $HOME/.ssh/wavetrack-deploy.pem
    # Add the EC2 instance to known hosts
    - ssh-keyscan -H ec2-54-164-58-149.compute-1.amazonaws.com >> $HOME/.ssh/known_hosts
    # Debugging: List the contents of the .ssh directory
    - ls -l $HOME/.ssh  # List files to ensure the key is there and permissions are correct
  script:
    - echo "Deploying frontend to EC2..."
    # Use the private key from the home directory
    - scp -i $HOME/.ssh/wavetrack-deploy.pem -r dist/ ubuntu@ec2-54-164-58-149.compute-1.amazonaws.com:/home/ubuntu/wavetrack-client
    - ssh -i $HOME/.ssh/wavetrack-deploy.pem ubuntu@ec2-54-164-58-149.compute-1.amazonaws.com "
      cd /home/ubuntu/wavetrack-client &&
      sudo systemctl restart my-frontend-service &&
      sudo systemctl restart nginx"
  environment:
    name: production
    url: https://web.vottamean.com
  only:
    - main
    - develop
