# Define pipeline stages
stages:
  - build
  - deploy

# Cache node_modules to speed up subsequent builds
cache:
  paths:
    - node_modules/

# Build job
build-frontend:
  stage: build
  image: node:20
  script:
    - echo "Installing frontend dependencies..."
    - npm install
    - export NODE_OPTIONS="--max-old-space-size=4096"
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  only:
    - main
    - develop

# Deploy job
deploy-frontend:
  stage: deploy
  image: docker:latest
  script:
    - echo "Deploying frontend to EC2..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/frontend:latest .
    - docker push $CI_REGISTRY_IMAGE/frontend:latest
    - ssh -o StrictHostKeyChecking=no ubuntu@ec2-184-73-16-169.compute-1.amazonaws.com "
      cd /home/ubuntu/wavetrack-client &&
      git pull origin main &&
      docker pull $CI_REGISTRY_IMAGE/frontend:latest &&
      docker-compose -f /home/ubuntu/wavetrack-client/docker-compose.yml up -d"
  environment:
    name: production
    url: https://web.vottamean.com
  only:
    - main
    - develop
