stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build-frontend:
  stage: build
  image: node:20
  script:
    - echo "Installing frontend dependencies..."
    - npm install
    - export NODE_OPTIONS="--max-old-space-size=4096" # Allows Node to use more memory during build
    - npm run build
  artifacts:
    paths:
      - dist/ # Store the built files for use in deployment
    expire_in: 1 week
  only:
    - main
    - develop

deploy-frontend:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Deploying frontend to EC2..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/frontend:latest .
    - docker push $CI_REGISTRY_IMAGE/frontend:latest
    - ssh -o StrictHostKeyChecking=no ubuntu@your-ec2-ip "
      docker pull $CI_REGISTRY_IMAGE/frontend:latest &&
      docker-compose -f /home/ubuntu/wavetrack-client/docker-compose.yml up -d"
  environment:
    name: production
    url: https://web.vottamean.com
  only:
    - main
    - develop
