version: '3'
services:
  client:
    image: 'git.clp.kr:5050/anbschool/2nd/hexcode/team-projects/wavetrack-client:latest'
    container_name: frontend
    restart: always
    ports:
      - '5173:80'
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge
