version: '3'
services:
  frontend:
    image: $CI_REGISTRY_IMAGE/frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost || exit 1" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
    working_dir: /usr/src/app
    command: "npm run preview"
