version: '3.8'
services:
  frontend:
    build:
      context: ./wavetrack-client
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost || exit 1" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
    working_dir: /app
    command: "npm run preview"
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
    deploy:
      resources:
        limits:
          memory: 1G
